"""
This type stub file was generated by pyright.
"""

import praw.models
from typing import Iterator, TYPE_CHECKING
from ...base import PRAWBase

"""Provide the RisingListingMixin class."""
if TYPE_CHECKING:
    ...
class RisingListingMixin(PRAWBase):
    """Mixes in the rising methods."""
    def random_rising(self, **generator_kwargs: str | int | dict[str, str]) -> Iterator[praw.models.Submission]:
        """Return a :class:`.ListingGenerator` for random rising submissions.

        Additional keyword arguments are passed in the initialization of
        :class:`.ListingGenerator`.

        For example, to get random rising submissions for r/test:

        .. code-block:: python

            for submission in reddit.subreddit("test").random_rising():
                print(submission.title)

        """
        ...
    
    def rising(self, **generator_kwargs: str | int | dict[str, str]) -> Iterator[praw.models.Submission]:
        """Return a :class:`.ListingGenerator` for rising submissions.

        Additional keyword arguments are passed in the initialization of
        :class:`.ListingGenerator`.

        For example, to get rising submissions for r/test:

        .. code-block:: python

            for submission in reddit.subreddit("test").rising():
                print(submission.title)

        """
        ...
    


